name: Descarga precio de hoy

on:
  workflow_dispatch:
  schedule:
    - cron: 0 7-18 * * *  # Invierno CET (UTC+1): 8h-19h España
    - cron: 0 6-17 * * *  # Verano CEST (UTC+2): 8h-19h España

env:
  GASOLINA_CHAT_ID: ${{ secrets.GASOLINA_CHAT_ID }}
  DIESEL_CHAT_ID: ${{ secrets.DIESEL_CHAT_ID }}
  TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}

jobs:
  downloadStatus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js version 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
    - run: npm install
    - name: Descarga gasolinera Barataria
      run: npm run download-today
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0'
        FUEL_STATION_ID: 5205
    - name: Descarga gasolinera Plaza de Toros
      run: npm run download-today
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0'
        FUEL_STATION_ID: 5143
        DATA_FILE: ./data-5143.json
    - name: Add prices
      id: auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Add report for today'
    - name: "Send to telegram if changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: npm run send
      env:
        DATA_FILE_2: ./data-5143.json
        STATION_NAME_1: Barataria
        STATION_NAME_2: Plaza de Toros
